USE SENAI_HROADS_TARDE

SELECT * FROM PERSONAGENS

SELECT * FROM CLASSE

SELECT NOME FROM CLASSE

SELECT * FROM HABILIDADES

SELECT COUNT(*) AS QUANTIDADE_TOTAL_REGISTROS FROM HABILIDADES

SELECT ID FROM HABILIDADES ORDER BY ID ASC

SELECT * FROM TIPO_HABILIDADE


SELECT H.NOME AS HABILIDADES,T.NOME AS TIPO_HABILIDADE

FROM
	HABILIDADES AS H INNER JOIN TIPO_HABILIDADE AS T
	
ON
	H.ID_TIPO_HABILIDADE = T.ID


SELECT P.NOME AS PERSONAGENS,C.NOME AS CLASSE

FROM
	PERSONAGENS AS P INNER JOIN CLASSE AS C
	
ON
	P.ID_CLASSE= C.ID


SELECT P.NOME AS PERSONAGENS,C.NOME AS CLASSE

FROM
	PERSONAGENS AS P RIGHT JOIN CLASSE AS C
	
ON
	P.ID_CLASSE= C.ID


SELECT CLASSE.NOME AS CLASSE,HABILIDADES.NOME AS HABILIDADES 

FROM CLASSE LEFT JOIN CLASSES_HABILIDADES 

ON (CLASSES_HABILIDADES.ID_CLASSE=CLASSE.ID) LEFT JOIN HABILIDADES 

ON (CLASSES_HABILIDADES.ID_HABILIDADE=HABILIDADES.ID)



SELECT HABILIDADES.NOME AS HABILIDADE,CLASSE.NOME AS CLASSE 

FROM HABILIDADES INNER JOIN CLASSES_HABILIDADES 

ON (CLASSES_HABILIDADES.ID_HABILIDADE=HABILIDADES.ID) INNER JOIN CLASSE

ON (CLASSES_HABILIDADES.ID_CLASSE=CLASSE.ID)


SELECT HABILIDADES.NOME AS HABILIDADE,CLASSE.NOME AS CLASSE 

FROM HABILIDADES LEFT JOIN CLASSES_HABILIDADES 

ON (CLASSES_HABILIDADES.ID_HABILIDADE=HABILIDADES.ID) RIGHT JOIN CLASSE

ON (CLASSES_HABILIDADES.ID_CLASSE=CLASSE.ID)



	
	
