USE SENAI_HROADS_TARDE

INSERT INTO PERSONAGENS(NOME,ID_CLASSE,CAPACIDADE_MAXIMA_VIDA,CAPACIDADE_MAXIMA_MANA,DATA_ATUALIZACAO,DATA_CRIACAO)
VALUES ('DeuBug',1,100,80,'04/02/2019','18/01/2018');
INSERT INTO PERSONAGENS(NOME,ID_CLASSE,CAPACIDADE_MAXIMA_VIDA,CAPACIDADE_MAXIMA_MANA,DATA_ATUALIZACAO,DATA_CRIACAO)
VALUES ('BitBug',4,70,100,'04/02/2019','17/03/2016'),
		('Fer8',7,75,60,'04/02/2019','18/03/2018')

INSERT INTO CLASSE(NOME)
VALUES ('Bárbaro'),('Cruzado'),('Caçadora De Demônios'),('Monge'),('Necromante'),('Feiticeiro'),('Arcanista')

INSERT INTO HABILIDADES(NOME,ID_TIPO_HABILIDADE)
VALUES ('Lança Mortal',1),('Escudo Supremo',2),('Recuperar Vida',3)

INSERT INTO TIPO_HABILIDADE(NOME)
VALUES ('Ataque'),('Defesa'),('Cura'),('Magia')

INSERT INTO CLASSES_HABILIDADES(ID_CLASSE,ID_HABILIDADE)
VALUES (1,1),(1,2),(2,2),(3,1),(4,3),(4,2),(6,3)

UPDATE PERSONAGENS SET NOME='Fer7' WHERE NOME='Fer8'

UPDATE CLASSE SET NOME='Necromancer' WHERE NOME='Necromante'


